import { EmployeeType } from "@/types/EmployeeType.tsx";

export const Employees: EmployeeType[] = [
    { id: 1, nombre: "Juan Pérez", puesto: "Desarrollador", sueldo: 50000 },
    { id: 2, nombre: "Ana López", puesto: "Diseñadora", sueldo: 48000 },
    { id: 3, nombre: "Carlos García", puesto: "Gerente de Proyecto", sueldo: 65000 },
    { id: 4, nombre: "María Hernández", puesto: "Analista", sueldo: 45000 },
    { id: 5, nombre: "Pedro Jiménez", puesto: "Desarrollador", sueldo: 52000 },
    { id: 6, nombre: "Laura Ortiz", puesto: "Marketing", sueldo: 47000 },
    { id: 7, nombre: "Daniela Ramos", puesto: "Soporte Técnico", sueldo: 42000 },
    { id: 8, nombre: "Luis Martínez", puesto: "Desarrollador", sueldo: 55000 },
    { id: 9, nombre: "Jorge Sánchez", puesto: "Diseñador UI/UX", sueldo: 49000 },
    { id: 10, nombre: "Carolina Ruiz", puesto: "Analista de Datos", sueldo: 53000 },
    { id: 11, nombre: "Fernando Flores", puesto: "Gerente de Ventas", sueldo: 62000 },
    { id: 12, nombre: "Raúl Delgado", puesto: "Soporte Técnico", sueldo: 41000 },
    { id: 13, nombre: "Carmen Castro", puesto: "Recursos Humanos", sueldo: 46000 },
    { id: 14, nombre: "Susana Vargas", puesto: "Administración", sueldo: 44000 },
    { id: 15, nombre: "Alberto Castillo", puesto: "Desarrollador", sueldo: 51000 },
    { id: 16, nombre: "Patricia Morales", puesto: "Analista Financiero", sueldo: 55000 },
    { id: 17, nombre: "Gabriel Rivera", puesto: "Diseñador Gráfico", sueldo: 48000 },
    { id: 18, nombre: "Diana Navarro", puesto: "SEO Specialist", sueldo: 50000 },
    { id: 19, nombre: "Rodrigo Peña", puesto: "Community Manager", sueldo: 43000 },
    { id: 20, nombre: "Silvia Guzmán", puesto: "Contador", sueldo: 54000 },
    { id: 21, nombre: "Ricardo Solís", puesto: "Ingeniero de DevOps", sueldo: 60000 },
    { id: 22, nombre: "Verónica Reyes", puesto: "Product Owner", sueldo: 67000 },
    { id: 23, nombre: "Mario Escobar", puesto: "Desarrollador Backend", sueldo: 53000 },
    { id: 24, nombre: "Sandra Beltrán", puesto: "QA Tester", sueldo: 45000 },
    { id: 25, nombre: "Nicolás Cabrera", puesto: "Data Scientist", sueldo: 72000 },
    { id: 26, nombre: "Isabel Vargas", puesto: "Especialista en Marketing Digital", sueldo: 46000 },
    { id: 27, nombre: "Andrés Torres", puesto: "Desarrollador Móvil", sueldo: 50000 },
    { id: 28, nombre: "Beatriz Soto", puesto: "Analista de Negocios", sueldo: 54000 },
    { id: 29, nombre: "Joaquín Ríos", puesto: "Administrador de Redes", sueldo: 48000 },
    { id: 30, nombre: "Lucía Delgado", puesto: "Asistente Ejecutiva", sueldo: 40000 },
    { id: 31, nombre: "Diego Marín", puesto: "Desarrollador Frontend", sueldo: 55000 },
    { id: 32, nombre: "Natalia Ortega", puesto: "Asistente Administrativa", sueldo: 39000 },
    { id: 33, nombre: "Marco López", puesto: "Ingeniero de Sistemas", sueldo: 72000 },
    { id: 34, nombre: "Gabriela Díaz", puesto: "Gerente de Marketing", sueldo: 75000 },
    { id: 35, nombre: "Arturo Méndez", puesto: "Desarrollador Full Stack", sueldo: 67000 },
    { id: 36, nombre: "Rocío Aguirre", puesto: "Diseñadora Gráfica", sueldo: 48000 },
    { id: 37, nombre: "David Silva", puesto: "Analista de Calidad", sueldo: 46000 },
    { id: 38, nombre: "Valentina Castro", puesto: "Consultora", sueldo: 62000 },
    { id: 39, nombre: "Ricardo Gómez", puesto: "Gerente de TI", sueldo: 70000 },
    { id: 40, nombre: "Clara Paredes", puesto: "Desarrolladora de Software", sueldo: 63000 },
    { id: 41, nombre: "Javier Morales", puesto: "Científico de Datos", sueldo: 75000 },
    { id: 42, nombre: "Patricia Silva", puesto: "Analista de Sistemas", sueldo: 49000 },
    { id: 43, nombre: "Fabián Romero", puesto: "Gerente de Operaciones", sueldo: 72000 },
    { id: 44, nombre: "Sofia Castañeda", puesto: "Especialista en SEO", sueldo: 58000 },
    { id: 45, nombre: "Cecilia Martínez", puesto: "Responsable de Proyectos", sueldo: 63000 },
    { id: 46, nombre: "Gonzalo Ruiz", puesto: "Arquitecto de Software", sueldo: 80000 },
    { id: 47, nombre: "Felipe Morales", puesto: "Administrador de Bases de Datos", sueldo: 65000 },
    { id: 48, nombre: "Mónica Hernández", puesto: "Diseñadora UX", sueldo: 50000 },
    { id: 49, nombre: "Osvaldo Salazar", puesto: "Ingeniero de Soporte", sueldo: 45000 },
    { id: 50, nombre: "Raúl Torres", puesto: "Consultor de Negocios", sueldo: 58000 },
    { id: 51, nombre: "Mauricio Delgado", puesto: "Desarrollador Móvil", sueldo: 52000 },
    { id: 52, nombre: "Fernando Alvarado", puesto: "Product Owner", sueldo: 67000 },
    { id: 53, nombre: "Elena Castro", puesto: "Analista de Datos", sueldo: 49000 },
    { id: 54, nombre: "Mario Fuentes", puesto: "Director de IT", sueldo: 85000 },
    { id: 55, nombre: "Samantha López", puesto: "Desarrolladora de Aplicaciones", sueldo: 58000 },
    { id: 56, nombre: "Erika Pérez", puesto: "Asistente de Recursos Humanos", sueldo: 40000 },
    { id: 57, nombre: "Luis Ríos", puesto: "Ingeniero de Calidad", sueldo: 62000 },
    { id: 58, nombre: "Lucía Aguirre", puesto: "Desarrolladora de Contenidos", sueldo: 53000 },
    { id: 59, nombre: "Sergio Ortega", puesto: "Gestor de Proyectos", sueldo: 68000 },
    { id: 60, nombre: "Patricia Espinoza", puesto: "Gerente de Producto", sueldo: 74000 },
    { id: 61, nombre: "María León", puesto: "Científica de Datos", sueldo: 75000 },
    { id: 62, nombre: "Fernando Ramírez", puesto: "Director Financiero", sueldo: 90000 },
    { id: 63, nombre: "Andrea Zamora", puesto: "Analista de Proyectos", sueldo: 54000 },
    { id: 64, nombre: "Rodrigo González", puesto: "Desarrollador de Software", sueldo: 65000 },
    { id: 65, nombre: "Rafael Hernández", puesto: "Ingeniero de Seguridad", sueldo: 78000 },
    { id: 66, nombre: "Claudia Vázquez", puesto: "Administradora de Redes", sueldo: 57000 },
    { id: 67, nombre: "Joaquín Castillo", puesto: "Analista de IT", sueldo: 51000 },
    { id: 68, nombre: "Sara Romero", puesto: "Desarrolladora Backend", sueldo: 62000 },
    { id: 69, nombre: "Oscar Salinas", puesto: "Ingeniero de DevOps", sueldo: 70000 },
    { id: 70, nombre: "Martina Cruz", puesto: "Directora de Marketing", sueldo: 82000 },
    { id: 71, nombre: "Julio López", puesto: "Desarrollador Frontend", sueldo: 59000 },
    { id: 72, nombre: "Diego Medina", puesto: "Gerente de Finanzas", sueldo: 77000 },
    { id: 73, nombre: "Natalia Ruiz", puesto: "Analista Financiero", sueldo: 50000 },
    { id: 74, nombre: "Fernando Herrera", puesto: "Consultor IT", sueldo: 63000 },
    { id: 75, nombre: "Juliana Sánchez", puesto: "Desarrolladora Full Stack", sueldo: 65000 },
    { id: 76, nombre: "Carla Ortega", puesto: "Asistente Administrativa", sueldo: 41000 },
    { id: 77, nombre: "Martin Castaño", puesto: "Gerente de Proyectos", sueldo: 75000 },
    { id: 78, nombre: "Gonzalo Castañeda", puesto: "Desarrollador de Sistemas", sueldo: 60000 },
    { id: 79, nombre: "Isabel Guzmán", puesto: "Desarrolladora de Software", sueldo: 62000 },
    { id: 80, nombre: "Victor Martínez", puesto: "Analista de Seguridad", sueldo: 49000 },
    { id: 81, nombre: "Nadia Pizarro", puesto: "Gerente de Ventas", sueldo: 71000 },
    { id: 82, nombre: "Fernando Ceballos", puesto: "Soporte Técnico", sueldo: 42000 },
    { id: 83, nombre: "Juanita Castro", puesto: "Administradora de TI", sueldo: 46000 },
    { id: 84, nombre: "Adriana López", puesto: "Desarrolladora de Aplicaciones", sueldo: 53000 },
    { id: 85, nombre: "Felipe Sandoval", puesto: "Ingeniero de Software", sueldo: 67000 },
    { id: 86, nombre: "Veronica Andrade", puesto: "Asistente de Proyectos", sueldo: 39000 },
    { id: 87, nombre: "Diego Vivas", puesto: "Ingeniero de Calidad", sueldo: 54000 },
    { id: 88, nombre: "Lucas Pacheco", puesto: "Desarrollador Frontend", sueldo: 61000 },
    { id: 89, nombre: "Alicia Castillo", puesto: "Diseñadora Gráfica", sueldo: 48000 },
    { id: 90, nombre: "Esteban Rojas", puesto: "Director de Proyectos", sueldo: 80000 },
    { id: 91, nombre: "Nicolás Salas", puesto: "Gerente de TI", sueldo: 79000 },
    { id: 92, nombre: "Marcela Ramírez", puesto: "Gerente de Recursos Humanos", sueldo: 73000 },
    { id: 93, nombre: "Julián Rodríguez", puesto: "Desarrollador de Software", sueldo: 60000 },
    { id: 94, nombre: "Renata Aguirre", puesto: "Analista de Sistemas", sueldo: 55000 },
    { id: 95, nombre: "Roberto Córdova", puesto: "Ingeniero de DevOps", sueldo: 71000 },
    { id: 96, nombre: "Paola Castillo", puesto: "Especialista en Marketing", sueldo: 49000 },
    { id: 97, nombre: "Matías Gómez", puesto: "Gerente de Proyectos", sueldo: 76000 },
    { id: 98, nombre: "Santiago Pérez", puesto: "Desarrollador Backend", sueldo: 64000 },
    { id: 99, nombre: "Tania Villanueva", puesto: "Consultora de TI", sueldo: 68000 },
    { id: 100, nombre: "Arturo Herrera", puesto: "Analista de Datos", sueldo: 52000 },
    { id: 101, nombre: "Evelyn Morales", puesto: "Asistente Administrativa", sueldo: 41000 },
    { id: 102, nombre: "Pedro Salazar", puesto: "Desarrollador Móvil", sueldo: 57000 },
    { id: 103, nombre: "Gisela Herrera", puesto: "Gerente de IT", sueldo: 83000 },
    { id: 104, nombre: "Joaquín López", puesto: "Ingeniero de Soporte", sueldo: 48000 },
    { id: 105, nombre: "Ángela Díaz", puesto: "Diseñadora UI/UX", sueldo: 50000 },
    { id: 106, nombre: "Cristina Ortega", puesto: "Científica de Datos", sueldo: 72000 },
    { id: 107, nombre: "Bernardo Romero", puesto: "Gerente de Ventas", sueldo: 69000 },
    { id: 108, nombre: "Clara Pérez", puesto: "Analista de Seguridad", sueldo: 46000 },
    { id: 109, nombre: "Luis Vera", puesto: "Desarrollador Full Stack", sueldo: 68000 },
    { id: 110, nombre: "Soledad Castro", puesto: "Asistente de Marketing", sueldo: 42000 },
    { id: 111, nombre: "Mario Aguirre", puesto: "Gerente de Marketing", sueldo: 75000 },
    { id: 112, nombre: "Julio Cortés", puesto: "Diseñador Gráfico", sueldo: 49000 },
    { id: 113, nombre: "Nicolás Sandoval", puesto: "Desarrollador Frontend", sueldo: 60000 },
    { id: 114, nombre: "Andrea Orozco", puesto: "Analista Financiero", sueldo: 55000 },
    { id: 115, nombre: "Raúl Vázquez", puesto: "Consultor de TI", sueldo: 60000 },
    { id: 116, nombre: "Alejandro Castro", puesto: "Ingeniero de Seguridad", sueldo: 70000 },
    { id: 117, nombre: "Alicia Romero", puesto: "Administradora de Sistemas", sueldo: 48000 },
    { id: 118, nombre: "Joaquín Martínez", puesto: "Desarrollador Backend", sueldo: 64000 },
    { id: 119, nombre: "Valeria Mendoza", puesto: "Científica de Datos", sueldo: 73000 },
    { id: 120, nombre: "Francisco Pérez", puesto: "Gerente de Operaciones", sueldo: 80000 },
    { id: 121, nombre: "Gabriel Serrano", puesto: "Desarrollador Móvil", sueldo: 57000 },
    { id: 122, nombre: "Patricia Salazar", puesto: "Asistente de Recursos Humanos", sueldo: 40000 },
    { id: 123, nombre: "Alejandra León", puesto: "Ingeniero de Calidad", sueldo: 62000 },
    { id: 124, nombre: "Diego González", puesto: "Analista de Sistemas", sueldo: 55000 },
    { id: 125, nombre: "Mariana Ruiz", puesto: "Desarrolladora de Software", sueldo: 68000 },
    { id: 126, nombre: "José Pérez", puesto: "Consultor de Negocios", sueldo: 59000 },
    { id: 127, nombre: "Camila López", puesto: "Asistente Administrativa", sueldo: 42000 },
    { id: 128, nombre: "Santiago Martínez", puesto: "Gerente de Finanzas", sueldo: 77000 },
    { id: 129, nombre: "María López", puesto: "Desarrolladora de Aplicaciones", sueldo: 64000 },
    { id: 130, nombre: "Fernando Mendoza", puesto: "Gerente de TI", sueldo: 75000 },
    { id: 131, nombre: "Eliana Fernández", puesto: "Diseñadora Gráfica", sueldo: 48000 },
    { id: 132, nombre: "Álvaro Salas", puesto: "Ingeniero de DevOps", sueldo: 70000 },
    { id: 133, nombre: "Martina Gómez", puesto: "Analista de Calidad", sueldo: 50000 },
    { id: 134, nombre: "Carlos Soto", puesto: "Desarrollador Frontend", sueldo: 59000 },
    { id: 135, nombre: "Natalia Reyes", puesto: "Asistente de Proyectos", sueldo: 42000 },
    { id: 136, nombre: "Luis Hernández", puesto: "Ingeniero de Sistemas", sueldo: 75000 },
    { id: 137, nombre: "Sofía Castro", puesto: "Científica de Datos", sueldo: 80000 },
    { id: 138, nombre: "Eduardo García", puesto: "Gerente de Marketing", sueldo: 72000 },
    { id: 139, nombre: "Diana Paredes", puesto: "Desarrolladora de Software", sueldo: 68000 },
    { id: 140, nombre: "Julio Castañeda", puesto: "Consultor IT", sueldo: 60000 },
    { id: 141, nombre: "Patricia López", puesto: "Asistente de Marketing", sueldo: 43000 },
    { id: 142, nombre: "Sebastián Torres", puesto: "Desarrollador Móvil", sueldo: 58000 },
    { id: 143, nombre: "Victoria Morales", puesto: "Analista de Negocios", sueldo: 54000 },
    { id: 144, nombre: "Arturo Reyes", puesto: "Gerente de Proyectos", sueldo: 79000 },
    { id: 145, nombre: "Carolina Mendoza", puesto: "Analista de Sistemas", sueldo: 55000 },
    { id: 146, nombre: "Juan García", puesto: "Ingeniero de Soporte", sueldo: 48000 },
    { id: 147, nombre: "Vanessa Castillo", puesto: "Asistente Administrativa", sueldo: 40000 },
    { id: 148, nombre: "Samuel Gómez", puesto: "Desarrollador de Aplicaciones", sueldo: 64000 },
    { id: 149, nombre: "Inés López", puesto: "Científica de Datos", sueldo: 72000 },
    { id: 150, nombre: "Esteban Salas", puesto: "Analista Financiero", sueldo: 51000 },
    { id: 151, nombre: "Cristina Pérez", puesto: "Desarrolladora Frontend", sueldo: 59000 },
    { id: 152, nombre: "José Salazar", puesto: "Gerente de Recursos Humanos", sueldo: 72000 },
    { id: 153, nombre: "Patricia Vargas", puesto: "Soporte Técnico", sueldo: 46000 },
    { id: 154, nombre: "Felipe Rodríguez", puesto: "Desarrollador Full Stack", sueldo: 65000 },
    { id: 155, nombre: "María Salazar", puesto: "Desarrolladora de Software", sueldo: 68000 },
    { id: 156, nombre: "Joaquín López", puesto: "Analista de Datos", sueldo: 52000 },
    { id: 157, nombre: "Sofia López", puesto: "Asistente Ejecutiva", sueldo: 40000 },
    { id: 158, nombre: "Jorge López", puesto: "Gerente de Proyectos", sueldo: 75000 },
    { id: 159, nombre: "Evelyn López", puesto: "Consultora de TI", sueldo: 68000 },
    { id: 160, nombre: "David Pérez", puesto: "Analista de Seguridad", sueldo: 46000 },
    { id: 161, nombre: "Marta González", puesto: "Diseñadora UI/UX", sueldo: 52000 },
    { id: 162, nombre: "Santiago Jiménez", puesto: "Desarrollador de Backend", sueldo: 60000 },
    { id: 163, nombre: "Patricia Muñoz", puesto: "Asistente Administrativa", sueldo: 41000 },
    { id: 164, nombre: "Julián Cortés", puesto: "Desarrollador Full Stack", sueldo: 67000 },
    { id: 165, nombre: "Ricardo López", puesto: "Analista de Negocios", sueldo: 54000 },
    { id: 166, nombre: "Ana Jiménez", puesto: "Administradora de Sistemas", sueldo: 48000 },
    { id: 167, nombre: "Daniel Gutiérrez", puesto: "Científico de Datos", sueldo: 75000 },
    { id: 168, nombre: "María López", puesto: "Ingeniero de DevOps", sueldo: 68000 },
    { id: 169, nombre: "Hugo Torres", puesto: "Gerente de Ventas", sueldo: 70000 },
    { id: 170, nombre: "Isabel Ortega", puesto: "Desarrolladora de Aplicaciones", sueldo: 64000 },
    { id: 171, nombre: "Nicolás Pérez", puesto: "Desarrollador Frontend", sueldo: 61000 },
    { id: 172, nombre: "Camilo Salazar", puesto: "Desarrollador Móvil", sueldo: 55000 },
    { id: 173, nombre: "Ángela Fernández", puesto: "Ingeniero de Soporte", sueldo: 47000 },
    { id: 174, nombre: "Raúl Orozco", puesto: "Asistente de Marketing", sueldo: 42000 },
    { id: 175, nombre: "Fernando Herrera", puesto: "Científico de Datos", sueldo: 72000 },
    { id: 176, nombre: "Tatiana Mendoza", puesto: "Desarrolladora de Software", sueldo: 68000 },
    { id: 177, nombre: "Martín Pizarro", puesto: "Gerente de TI", sueldo: 75000 },
    { id: 178, nombre: "Diego Castro", puesto: "Desarrollador de Backend", sueldo: 60000 },
    { id: 179, nombre: "Camila Vargas", puesto: "Asistente de Recursos Humanos", sueldo: 40000 },
    { id: 180, nombre: "Sofía Rojas", puesto: "Analista de Calidad", sueldo: 50000 },
    { id: 181, nombre: "David Ramos", puesto: "Ingeniero de Calidad", sueldo: 67000 },
    { id: 182, nombre: "Alejandro López", puesto: "Desarrollador Frontend", sueldo: 61000 },
    { id: 183, nombre: "Valeria Pérez", puesto: "Analista Financiero", sueldo: 55000 },
    { id: 184, nombre: "Francisco Jiménez", puesto: "Científico de Datos", sueldo: 70000 },
    { id: 185, nombre: "Sebastián López", puesto: "Consultor de TI", sueldo: 60000 },
    { id: 186, nombre: "Cristina Salas", puesto: "Diseñadora Gráfica", sueldo: 50000 },
    { id: 187, nombre: "Eduardo Torres", puesto: "Desarrollador de Software", sueldo: 68000 },
    { id: 188, nombre: "Mauricio González", puesto: "Analista de Sistemas", sueldo: 54000 },
    { id: 189, nombre: "Renata Castro", puesto: "Gerente de Proyectos", sueldo: 78000 },
    { id: 190, nombre: "Gustavo Rojas", puesto: "Desarrollador Backend", sueldo: 64000 },
    { id: 191, nombre: "Gabriela Díaz", puesto: "Asistente Administrativa", sueldo: 42000 },
    { id: 192, nombre: "Pablo Jiménez", puesto: "Ingeniero de Software", sueldo: 67000 },
    { id: 193, nombre: "Eliana Pérez", puesto: "Desarrolladora de Software", sueldo: 60000 },
    { id: 194, nombre: "José Luis Mendoza", puesto: "Consultor IT", sueldo: 68000 },
    { id: 195, nombre: "Gabriela López", puesto: "Analista de Seguridad", sueldo: 50000 },
    { id: 196, nombre: "Fernando Vargas", puesto: "Ingeniero de Sistemas", sueldo: 71000 },
    { id: 197, nombre: "Juliana Pérez", puesto: "Científica de Datos", sueldo: 74000 },
    { id: 198, nombre: "Nicolás González", puesto: "Desarrollador Móvil", sueldo: 56000 },
    { id: 199, nombre: "Lucía Aguirre", puesto: "Asistente de Proyectos", sueldo: 43000 },
    { id: 200, nombre: "Andrés López", puesto: "Desarrollador Full Stack", sueldo: 65000 },
    { id: 201, nombre: "Manuela Castillo", puesto: "Asistente Administrativa", sueldo: 41000 },
    { id: 202, nombre: "Jorge Castro", puesto: "Gerente de Finanzas", sueldo: 79000 },
    { id: 203, nombre: "Alberto Medina", puesto: "Ingeniero de DevOps", sueldo: 72000 },
    { id: 204, nombre: "Martín Torres", puesto: "Desarrollador de Software", sueldo: 66000 },
    { id: 205, nombre: "Valentina Morales", puesto: "Analista de Negocios", sueldo: 54000 },
    { id: 206, nombre: "Fernando Gómez", puesto: "Gerente de Proyectos", sueldo: 80000 },
    { id: 207, nombre: "Isabel Sánchez", puesto: "Desarrolladora de Aplicaciones", sueldo: 64000 },
    { id: 208, nombre: "Ricardo Rodríguez", puesto: "Científico de Datos", sueldo: 75000 },
    { id: 209, nombre: "Rafael Pérez", puesto: "Desarrollador Backend", sueldo: 59000 },
    { id: 210, nombre: "Cristina López", puesto: "Asistente Ejecutiva", sueldo: 40000 },
    { id: 211, nombre: "Joaquín Ramírez", puesto: "Gerente de Ventas", sueldo: 72000 },
    { id: 212, nombre: "Luis Castro", puesto: "Analista de Sistemas", sueldo: 57000 },
    { id: 213, nombre: "Adriana Rodríguez", puesto: "Desarrolladora de Software", sueldo: 68000 },
    { id: 214, nombre: "Fernando Ceballos", puesto: "Desarrollador de Frontend", sueldo: 61000 },
    { id: 215, nombre: "Esteban Aguirre", puesto: "Consultor IT", sueldo: 65000 },
    { id: 216, nombre: "María Medina", puesto: "Asistente de Recursos Humanos", sueldo: 40000 },
    { id: 217, nombre: "Alfonso Sánchez", puesto: "Gerente de TI", sueldo: 79000 },
    { id: 218, nombre: "Sandra López", puesto: "Analista Financiero", sueldo: 55000 },
    { id: 219, nombre: "Camilo Jiménez", puesto: "Desarrollador Full Stack", sueldo: 67000 },
    { id: 220, nombre: "Lina Castillo", puesto: "Diseñadora UI/UX", sueldo: 50000 },
    { id: 221, nombre: "Mario Pérez", puesto: "Ingeniero de Calidad", sueldo: 64000 },
    { id: 222, nombre: "Carmen Medina", puesto: "Asistente Administrativa", sueldo: 43000 },
    { id: 223, nombre: "Elena Torres", puesto: "Científica de Datos", sueldo: 72000 },
    { id: 224, nombre: "Hugo Jiménez", puesto: "Desarrollador de Backend", sueldo: 64000 },
    { id: 225, nombre: "Sandra Martínez", puesto: "Gerente de Recursos Humanos", sueldo: 78000 },
        { id: 226, nombre: "Gabriel Martínez", puesto: "Desarrollador Frontend", sueldo: 59000 },
        { id: 227, nombre: "Claudia Gómez", puesto: "Analista de Negocios", sueldo: 53000 },
        { id: 228, nombre: "Fernando Pérez", puesto: "Consultor IT", sueldo: 61000 },
        { id: 229, nombre: "Diana Rodríguez", puesto: "Asistente de Proyectos", sueldo: 40000 },
        { id: 230, nombre: "Laura Salas", puesto: "Desarrolladora de Software", sueldo: 68000 },
        { id: 231, nombre: "Álvaro Castro", puesto: "Gerente de Finanzas", sueldo: 77000 },
        { id: 232, nombre: "Lucas López", puesto: "Desarrollador de Móvil", sueldo: 57000 },
        { id: 233, nombre: "Patricia Jiménez", puesto: "Asistente Administrativa", sueldo: 42000 },
        { id: 234, nombre: "Esteban López", puesto: "Científico de Datos", sueldo: 71000 },
        { id: 235, nombre: "Julián Aguirre", puesto: "Desarrollador Backend", sueldo: 65000 },
        { id: 236, nombre: "Joaquín Mendoza", puesto: "Ingeniero de Software", sueldo: 68000 },
        { id: 237, nombre: "Martina Castaño", puesto: "Asistente de Recursos Humanos", sueldo: 40000 },
        { id: 238, nombre: "Fernando Salazar", puesto: "Desarrollador de Frontend", sueldo: 60000 },
        { id: 239, nombre: "Gabriela Ramírez", puesto: "Administradora de Sistemas", sueldo: 48000 },
        { id: 240, nombre: "Santiago López", puesto: "Gerente de Proyectos", sueldo: 80000 },
        { id: 241, nombre: "Fernando Pérez", puesto: "Ingeniero de Seguridad", sueldo: 69000 },
        { id: 242, nombre: "Sebastián Castro", puesto: "Analista de Sistemas", sueldo: 57000 },
        { id: 243, nombre: "Patricia Torres", puesto: "Asistente Administrativa", sueldo: 42000 },
        { id: 244, nombre: "Lucía Martínez", puesto: "Desarrolladora de Aplicaciones", sueldo: 65000 },
        { id: 245, nombre: "David Aguirre", puesto: "Científico de Datos", sueldo: 74000 },
        { id: 246, nombre: "Clara López", puesto: "Analista Financiero", sueldo: 52000 },
        { id: 247, nombre: "Álvaro Reyes", puesto: "Gerente de TI", sueldo: 83000 },
        { id: 248, nombre: "Laura Martínez", puesto: "Desarrolladora de Software", sueldo: 69000 },
        { id: 249, nombre: "Cristian Torres", puesto: "Asistente de Proyectos", sueldo: 40000 },
        { id: 250, nombre: "Valeria Castillo", puesto: "Ingeniero de Soporte", sueldo: 48000 },
        { id: 251, nombre: "Natalia Salazar", puesto: "Desarrolladora Full Stack", sueldo: 67000 },
        { id: 252, nombre: "David Rojas", puesto: "Desarrollador Móvil", sueldo: 59000 },
        { id: 253, nombre: "Gabriel Pérez", puesto: "Analista de Seguridad", sueldo: 54000 },
        { id: 254, nombre: "Sofia Castillo", puesto: "Gerente de Recursos Humanos", sueldo: 73000 },
        { id: 255, nombre: "Santiago Torres", puesto: "Desarrollador de Backend", sueldo: 61000 },
        { id: 256, nombre: "Elena Salazar", puesto: "Asistente Administrativa", sueldo: 41000 },
        { id: 257, nombre: "Manuel Gómez", puesto: "Científico de Datos", sueldo: 78000 },
        { id: 258, nombre: "Lucas Martínez", puesto: "Desarrollador Full Stack", sueldo: 65000 },
        { id: 259, nombre: "Gabriela Ramírez", puesto: "Gerente de TI", sueldo: 79000 },
        { id: 260, nombre: "Natalia Pérez", puesto: "Analista de Sistemas", sueldo: 53000 },
        { id: 261, nombre: "Juanita Rodríguez", puesto: "Asistente de Recursos Humanos", sueldo: 40000 },
        { id: 262, nombre: "Leonardo Pérez", puesto: "Gerente de Finanzas", sueldo: 76000 },
        { id: 263, nombre: "Joaquín Jiménez", puesto: "Desarrollador de Móvil", sueldo: 58000 },
        { id: 264, nombre: "Inés López", puesto: "Asistente Administrativa", sueldo: 43000 },
        { id: 265, nombre: "Miguel Álvarez", puesto: "Científico de Datos", sueldo: 73000 },
        { id: 266, nombre: "Juan Pérez", puesto: "Consultor IT", sueldo: 60000 },
        { id: 267, nombre: "Valeria Jiménez", puesto: "Desarrolladora de Aplicaciones", sueldo: 64000 },
        { id: 268, nombre: "Adriana Torres", puesto: "Asistente de Marketing", sueldo: 42000 },
        { id: 269, nombre: "Manuela Castaño", puesto: "Administradora de Sistemas", sueldo: 48000 },
        { id: 270, nombre: "Roberto Salazar", puesto: "Desarrollador Full Stack", sueldo: 68000 },
        { id: 271, nombre: "Camilo González", puesto: "Gerente de Proyectos", sueldo: 80000 },
        { id: 272, nombre: "Carolina Pizarro", puesto: "Analista Financiero", sueldo: 55000 },
        { id: 273, nombre: "Mónica Pérez", puesto: "Desarrolladora de Software", sueldo: 67000 },
        { id: 274, nombre: "Alejandro Aguirre", puesto: "Desarrollador Backend", sueldo: 62000 },
        { id: 275, nombre: "Felipe López", puesto: "Asistente de Proyectos", sueldo: 41000 },
        { id: 276, nombre: "Laura Castaño", puesto: "Científica de Datos", sueldo: 78000 },
        { id: 277, nombre: "Juan Martínez", puesto: "Gerente de Marketing", sueldo: 74000 },
        { id: 278, nombre: "Juliana López", puesto: "Desarrolladora de Aplicaciones", sueldo: 67000 },
        { id: 279, nombre: "Carlos Salazar", puesto: "Ingeniero de Soporte", sueldo: 48000 },
        { id: 280, nombre: "Valentina Torres", puesto: "Asistente Administrativa", sueldo: 41000 },
        { id: 281, nombre: "Patricia Ruiz", puesto: "Consultor de TI", sueldo: 60000 },
        { id: 282, nombre: "Gabriel Ceballos", puesto: "Desarrollador de Frontend", sueldo: 59000 },
        { id: 283, nombre: "Carmen Pérez", puesto: "Analista de Sistemas", sueldo: 54000 },
        { id: 284, nombre: "Santiago López", puesto: "Asistente de Recursos Humanos", sueldo: 40000 },
        { id: 285, nombre: "Daniel Salazar", puesto: "Ingeniero de Calidad", sueldo: 64000 },
        { id: 286, nombre: "Alfonso Jiménez", puesto: "Desarrollador Full Stack", sueldo: 67000 },
        { id: 287, nombre: "Cristina Castro", puesto: "Gerente de TI", sueldo: 78000 },
        { id: 288, nombre: "Camila Morales", puesto: "Desarrolladora de Software", sueldo: 68000 },
        { id: 289, nombre: "Juan Carlos López", puesto: "Asistente de Proyectos", sueldo: 40000 },
        { id: 290, nombre: "María Salas", puesto: "Ingeniero de Soporte", sueldo: 48000 },
        { id: 291, nombre: "Rafael López", puesto: "Científico de Datos", sueldo: 74000 },
        { id: 292, nombre: "Elena López", puesto: "Analista de Calidad", sueldo: 50000 },
        { id: 293, nombre: "Pablo Vargas", puesto: "Gerente de Marketing", sueldo: 74000 },
        { id: 294, nombre: "Alejandra Ramírez", puesto: "Desarrolladora de Aplicaciones", sueldo: 64000 },
        { id: 295, nombre: "Gabriel Pérez", puesto: "Consultor IT", sueldo: 60000 },
        { id: 296, nombre: "Natalia López", puesto: "Asistente Administrativa", sueldo: 42000 },
        { id: 297, nombre: "Luis Fernández", puesto: "Científico de Datos", sueldo: 75000 },
        { id: 298, nombre: "Verónica Aguirre", puesto: "Desarrolladora Full Stack", sueldo: 67000 },
        { id: 299, nombre: "Sergio Martínez", puesto: "Desarrollador de Software", sueldo: 68000 },
        { id: 300, nombre: "Carla López", puesto: "Asistente Ejecutiva", sueldo: 40000 }
]


